"""Storage interface for Project A RAG Platform."""
from __future__ import annotations

from abc import ABC, abstractmethod


class Store(ABC):
    @abstractmethod
    def create_job(self, job: dict) -> None: ...
    @abstractmethod
    def get_job(self, job_id: str) -> dict | None: ...
    @abstractmethod
    def update_job(self, job: dict) -> None: ...
    @abstractmethod
    def upsert_job(self, job: dict) -> None: ...
    @abstractmethod
    def list_jobs(self, limit: int = 100) -> list[dict]: ...
    @abstractmethod
    def claim_next_job(self, worker_id: str) -> dict | None: ...
    @abstractmethod
    def list_chat_records(self) -> list: ...
    @abstractmethod
    def list_audit_events(self, limit: int = 100) -> list[dict]: ...
    @abstractmethod
    def record_audit_event(self, event: dict) -> None: ...
