/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics Endpoint */
        get: operations["metrics_endpoint_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acceptance/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Acceptance Overview */
        get: operations["acceptance_overview_api_v1_acceptance_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Documents */
        post: operations["ingest_documents_api_v1_documents_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Chat */
        post: operations["session_chat_api_v1_chat_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Ticket */
        post: operations["start_ticket_api_v1_tickets_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Ticket */
        post: operations["resume_ticket_api_v1_tickets__ticket_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Ticket */
        post: operations["close_ticket_api_v1_tickets__ticket_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_v1_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Evaluation */
        post: operations["run_evaluation_api_v1_evaluations_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events */
        get: operations["list_audit_events_api_v1_admin_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Ingest Job */
        post: operations["create_ingest_job_api_v1_jobs_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Evaluation Job */
        post: operations["create_evaluation_job_api_v1_jobs_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptanceBreakdownItem */
        AcceptanceBreakdownItem: {
            /** Label */
            label: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Metrics */
            metrics?: {
                [key: string]: string;
            };
        };
        /** AcceptanceChartBar */
        AcceptanceChartBar: {
            /** Label */
            label: string;
            /** Value */
            value: number;
            /**
             * Total
             * @default 1
             */
            total: number;
            /**
             * Tone
             * @default info
             */
            tone: string;
        };
        /** AcceptanceEvidenceItem */
        AcceptanceEvidenceItem: {
            /** Label */
            label: string;
            /** Path */
            path: string;
        };
        /** AcceptanceHighlightItem */
        AcceptanceHighlightItem: {
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Status */
            status: string;
            /** Tags */
            tags?: string[];
        };
        /** AcceptanceOverviewResponse */
        AcceptanceOverviewResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Generated From */
            generated_from: string[];
            /** Panels */
            panels: components["schemas"]["AcceptancePanel"][];
        };
        /** AcceptancePanel */
        AcceptancePanel: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Metrics */
            metrics: {
                [key: string]: string;
            };
            /** Evidence */
            evidence?: components["schemas"]["AcceptanceEvidenceItem"][];
            /** Breakdown */
            breakdown?: components["schemas"]["AcceptanceBreakdownItem"][];
            /** Chart */
            chart?: components["schemas"]["AcceptanceChartBar"][];
            /** Highlights */
            highlights?: components["schemas"]["AcceptanceHighlightItem"][];
            /** Trace Cases */
            trace_cases?: components["schemas"]["AcceptanceTraceCase"][];
        };
        /** AcceptanceTraceCase */
        AcceptanceTraceCase: {
            /** Case Id */
            case_id: string;
            /** Title */
            title: string;
            /** Issue */
            issue: string;
            /** Events */
            events?: components["schemas"]["AcceptanceTraceEvent"][];
            /** Raw Trace */
            raw_trace?: {
                [key: string]: unknown;
            };
        };
        /** AcceptanceTraceEvent */
        AcceptanceTraceEvent: {
            /** Name */
            name: string;
            /** Summary */
            summary: string;
            /** Inputs */
            inputs?: {
                [key: string]: string;
            };
            /** Outputs */
            outputs?: {
                [key: string]: string;
            };
            /** Metadata */
            metadata?: {
                [key: string]: string;
            };
        };
        /** AuditEventResponse */
        AuditEventResponse: {
            /** Action */
            action: string;
            /**
             * Actor Role
             * @default
             */
            actor_role: string;
            /**
             * Resource Type
             * @default
             */
            resource_type: string;
            /**
             * Resource Id
             * @default
             */
            resource_id: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Timestamp
             * @default
             */
            timestamp: string;
        };
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /** File */
            file: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /**
             * Llm Used
             * @default false
             */
            llm_used: boolean;
            /**
             * Insufficient
             * @default false
             */
            insufficient: boolean;
            /**
             * Safety Warning
             * @default false
             */
            safety_warning: boolean;
        };
        /** Citation */
        Citation: {
            /** Source */
            source: string;
            /** Chunk Index */
            chunk_index: number;
            /** Content */
            content: string;
        };
        /** EvaluationRunRequest */
        EvaluationRunRequest: {
            /** Evaluation Type */
            evaluation_type: string;
            /** Cases Path */
            cases_path: string;
            /**
             * Docs Source
             * @default seed_docs
             */
            docs_source: string;
        };
        /** EvaluationRunResponse */
        EvaluationRunResponse: {
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Report Path */
            report_path?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestRequest */
        IngestRequest: {
            /**
             * Docs Source
             * @default seed_docs
             */
            docs_source: string;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Document Count */
            document_count: number;
            /** Chunk Count */
            chunk_count: number;
        };
        /** JobCancelRequest */
        JobCancelRequest: {
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** JobCreateResponse */
        JobCreateResponse: {
            job: components["schemas"]["JobRecord"];
        };
        /** JobEvaluationRequest */
        JobEvaluationRequest: {
            /**
             * Evaluation Type
             * @default regression
             */
            evaluation_type: string;
            /**
             * Cases Path
             * @default
             */
            cases_path: string;
            /**
             * Docs Source
             * @default seed_docs
             */
            docs_source: string;
        };
        /** JobIngestRequest */
        JobIngestRequest: {
            /**
             * Docs Source
             * @default seed_docs
             */
            docs_source: string;
        };
        /** JobRecord */
        JobRecord: {
            /** Job Id */
            job_id: string;
            /**
             * Job Type
             * @default
             */
            job_type: string;
            /**
             * Status
             * @default PENDING
             */
            status: string;
            /**
             * Payload
             * @default {}
             */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Result
             * @default {}
             */
            result: {
                [key: string]: unknown;
            };
            /** Error */
            error?: string | null;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /**
             * Max Retries
             * @default 3
             */
            max_retries: number;
            /** Locked By */
            locked_by?: string | null;
            /** Locked At */
            locked_at?: string | null;
            /** Heartbeat At */
            heartbeat_at?: string | null;
            /**
             * Timeout Seconds
             * @default 300
             */
            timeout_seconds: number;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /** PartCandidate */
        PartCandidate: {
            /** Part Id */
            part_id: string;
            /** Name */
            name: string;
            /** Device Model */
            device_model: string;
            /** Reason */
            reason: string;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "LOW" | "MEDIUM" | "HIGH";
        /** SessionChatRequest */
        SessionChatRequest: {
            /** Session Id */
            session_id: string;
            /** Question */
            question: string;
        };
        /** SessionChatResponse */
        SessionChatResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /**
             * Llm Used
             * @default false
             */
            llm_used: boolean;
            /**
             * Insufficient
             * @default false
             */
            insufficient: boolean;
            /**
             * Safety Warning
             * @default false
             */
            safety_warning: boolean;
            /** Session Id */
            session_id: string;
            /** Resolved Question */
            resolved_question: string;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Release Url */
            release_url: string;
            /** Llm Provider */
            llm_provider: string;
            /** Llm Model */
            llm_model: string;
            /** Llm Enabled */
            llm_enabled: boolean;
            /** Vector Store Ready */
            vector_store_ready: boolean;
            /** Docs Sources */
            docs_sources: string[];
        };
        /** TicketCloseRequest */
        TicketCloseRequest: {
            /** Closed By */
            closed_by: string;
        };
        /** TicketRecord */
        TicketRecord: {
            /** Ticket Id */
            ticket_id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Question */
            question: string;
            /** Diagnosis */
            diagnosis: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /** Device Model */
            device_model?: string | null;
            /** Fault Code */
            fault_code?: string | null;
            /** @default LOW */
            risk_level: components["schemas"]["RiskLevel"];
            /** @default NEW */
            status: components["schemas"]["TicketStatus"];
            /** Required Parts */
            required_parts?: components["schemas"]["PartCandidate"][];
            /**
             * Human Required
             * @default false
             */
            human_required: boolean;
            /** Human Decision */
            human_decision?: string | null;
            /** Human Reviewer */
            human_reviewer?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Closed By */
            closed_by?: string | null;
            /** Closed At */
            closed_at?: string | null;
        };
        /** TicketResumeRequest */
        TicketResumeRequest: {
            /** Reviewer */
            reviewer: string;
            /** Decision */
            decision: string;
        };
        /** TicketStartRequest */
        TicketStartRequest: {
            /** Question */
            question: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /**
         * TicketStatus
         * @enum {string}
         */
        TicketStatus: "NEW" | "DIAGNOSED" | "NEED_PARTS" | "NEED_HUMAN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED";
        /** TicketWorkflowResult */
        TicketWorkflowResult: {
            ticket: components["schemas"]["TicketRecord"];
            /** Next Action */
            next_action: string;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Filename */
            filename: string;
            /** Path */
            path: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_endpoint_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    acceptance_overview_api_v1_acceptance_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptanceOverviewResponse"];
                };
            };
        };
    };
    ingest_documents_api_v1_documents_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IngestRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_chat_api_v1_chat_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_ticket_api_v1_tickets_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketWorkflowResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_ticket_api_v1_tickets__ticket_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketWorkflowResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_ticket_api_v1_tickets__ticket_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCloseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_api_v1_tickets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRecord"][];
                };
            };
        };
    };
    run_evaluation_api_v1_evaluations_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_api_v1_admin_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ingest_job_api_v1_jobs_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_job_api_v1_jobs_evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
